name: Run pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
        # cache: 'pip'
    - name: Install pipenv and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.lock
        pip install -r requirements-dev.lock
    - name: Run test
      run: |
        pytest
